const usersData = localStorage.getItem("usersData");
const busData = localStorage.getItem("busesData");

if (usersData === null) {
  console.log("setting users data");
  const setUsersData = [
    {
      emailId: "nagarjuna@gmail.com",
      password: "polavarapu97@",
      bookedTickets: [],
    },
  ];
  localStorage.setItem("usersData", JSON.stringify(setUsersData));
}

if (busData === null) {
  const setBusData = [
    {
      name: "APSRTC1120",
      departureLocation: "Vijayawada",
      destination: "Hyderabad",
      departureTime: [21, 30],
      arraivalTime: [4, 45],
      rating: 4.2,
      tickets: 30,
      price: 450,
      type: "Non-AC",
      bookedTickets: {},
    },
    {
      name: "APSRTC1121",
      departureLocation: "Vijayawada",
      destination: "Hyderabad",
      departureTime: [20, 30],
      arraivalTime: [4, 45],
      rating: 4.5,
      tickets: 30,
      price: 650,
      type: "AC",
      bookedTickets: {},
    },
    {
      name: "TSRTC1120",
      destination: "Vijayawada",
      departureLocation: "Hyderabad",
      departureTime: [20, 30],
      arraivalTime: [5, 45],
      rating: 4.4,
      tickets: 30,
      price: 550,
      type: "Non-AC",
      bookedTickets: {},
    },
    {
      name: "TSRTC1122",
      destination: "Bangalore",
      departureLocation: "Hyderabad",
      departureTime: [21, 30],
      arraivalTime: [10, 45],
      rating: 4.0,
      tickets: 30,
      price: 1050,
      type: "AC",
      bookedTickets: {},
    },
    {
      name: "BANG1123",
      departureLocation: "Bangalore",
      destination: "Hyderabad",
      departureTime: [21, 30],
      arraivalTime: [9, 45],
      rating: 3.7,
      tickets: 30,
      price: 850,
      type: "Non-AC",
      bookedTickets: {},
    },
    {
      name: "TSRTC1131",
      departureLocation: "Bangalore",
      destination: "Hyderabad",
      departureTime: [22, 30],
      arraivalTime: [10, 45],
      rating: 4.0,
      tickets: 30,
      price: 1150,
      type: "AC",
      bookedTickets: {},
    },
    {
      name: "BANG1132",
      destination: "Bangalore",
      departureLocation: "Hyderabad",
      departureTime: [20, 30],
      arraivalTime: [9, 45],
      rating: 3.7,
      tickets: 30,
      price: 850,
      type: "Non-AC",
      bookedTickets: {},
    },
    {
      name: "APSRTC1126",
      destination: "Bangalore",
      departureLocation: "Vijayawada",
      departureTime: [21, 30],
      arraivalTime: [8, 45],
      rating: 4.2,
      tickets: 30,
      price: 1050,
      type: "AC",
      bookedTickets: {},
    },
    {
      name: "BANG1120",
      destination: "Vijayawada",
      departureLocation: "Bangalore",
      departureTime: [21, 30],
      arraivalTime: [7, 45],
      rating: 4.4,
      tickets: 30,
      price: 900,
      type: "Non-AC",
      bookedTickets: {},
    },
    {
      name: "APSRTC1220",
      destination: "Vijayawada",
      departureLocation: "Goa",
      departureTime: [21, 30],
      arraivalTime: [10, 45],
      rating: 4.4,
      tickets: 30,
      price: 900,
      type: "Non-AC",
      bookedTickets: {},
    },
    {
      name: "APSRTC1221",
      destination: "Vijayawada",
      departureLocation: "Goa",
      departureTime: [22, 30],
      arraivalTime: [10, 45],
      rating: 4.4,
      tickets: 30,
      price: 1200,
      type: "AC",
      bookedTickets: {},
    },
    {
      name: "GOA1220",
      departureLocation: "Vijayawada",
      destination: "Goa",
      departureTime: [21, 30],
      arraivalTime: [10, 45],
      rating: 4.4,
      tickets: 30,
      price: 900,
      type: "Non-AC",
      bookedTickets: {},
    },
    {
      name: "GOA1221",
      departureLocation: "Vijayawada",
      destination: "Goa",
      departureTime: [22, 30],
      arraivalTime: [10, 45],
      rating: 4.4,
      tickets: 30,
      price: 1200,
      type: "AC",
      bookedTickets: {},
    },

    {
      name: "TSRTC1220",
      destination: "Hyderabad",
      departureLocation: "Goa",
      departureTime: [21, 30],
      arraivalTime: [10, 45],
      rating: 4.4,
      tickets: 30,
      price: 900,
      type: "Non-AC",
      bookedTickets: {},
    },
    {
      name: "TSRTC1221",
      destination: "Hyderabad",
      departureLocation: "Goa",
      departureTime: [22, 30],
      arraivalTime: [10, 45],
      rating: 4.4,
      tickets: 30,
      price: 1200,
      type: "AC",
      bookedTickets: {},
    },
    {
      name: "GOA1227",
      departureLocation: "Hyderabad",
      destination: "Goa",
      departureTime: [21, 30],
      arraivalTime: [10, 45],
      rating: 4.4,
      tickets: 30,
      price: 900,
      type: "Non-AC",
      bookedTickets: {},
    },
    {
      name: "GOA1228",
      departureLocation: "Hyderabad",
      destination: "Goa",
      departureTime: [22, 30],
      arraivalTime: [10, 45],
      rating: 4.4,
      tickets: 30,
      price: 1200,
      type: "AC",
      bookedTickets: {},
    },
    //
    {
      name: "BANG1220",
      destination: "Bangalore",
      departureLocation: "Goa",
      departureTime: [21, 30],
      arraivalTime: [10, 45],
      rating: 4.4,
      tickets: 30,
      price: 900,
      type: "Non-AC",
      bookedTickets: {},
    },
    {
      name: "BANG1221",
      destination: "Bangalore",
      departureLocation: "Goa",
      departureTime: [22, 30],
      arraivalTime: [10, 45],
      rating: 4.4,
      tickets: 30,
      price: 1200,
      type: "AC",
      bookedTickets: {},
    },
    {
      name: "GOA1229",
      departureLocation: "Bangalore",
      destination: "Goa",
      departureTime: [21, 30],
      arraivalTime: [10, 45],
      rating: 4.4,
      tickets: 30,
      price: 900,
      type: "Non-AC",
      bookedTickets: {},
    },
    {
      name: "GOA1230",
      departureLocation: "Bangalore",
      destination: "Goa",
      departureTime: [22, 30],
      arraivalTime: [10, 45],
      rating: 4.4,
      tickets: 30,
      price: 1200,
      type: "AC",
      bookedTickets: {},
    },
  ];
  localStorage.setItem("busesData", JSON.stringify(setBusData));
}
